"""Export service for PDF, CSV, and JSON report generation."""
import io
import csv
import json
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ExportService:
    """Generate downloadable reports in multiple formats."""

    def export_json(self, data: dict | list) -> bytes:
        """Export data as JSON."""
        return json.dumps(data, indent=2, default=str, ensure_ascii=False).encode("utf-8")

    def export_csv(self, data: list[dict]) -> bytes:
        """Export a list of dicts as CSV."""
        if not data:
            return b"No data to export."

        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=data[0].keys())
        writer.writeheader()
        for row in data:
            writer.writerow(row)
        return output.getvalue().encode("utf-8")

    def export_pdf(self, data: dict, title: str = "Password Analysis Report") -> bytes:
        """Export analysis data as a PDF report."""
        try:
            from fpdf import FPDF
        except ImportError:
            logger.error("fpdf2 not installed. Cannot generate PDF.")
            return b"PDF generation requires fpdf2 package."

        pdf = FPDF(orientation="P", unit="mm", format="A4")
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Header
        pdf.set_fill_color(10, 14, 26)
        pdf.rect(0, 0, 210, 40, "F")
        pdf.set_text_color(0, 212, 255)
        pdf.set_font("Helvetica", "B", 20)
        pdf.cell(0, 15, "Password Security Report", ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(200, 210, 220)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True, align="C")
        pdf.ln(15)

        # Content
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, title, ln=True)
        pdf.ln(5)

        pdf.set_font("Helvetica", "", 11)

        analysis = data.get("analysis", {})
        if analysis:
            self._pdf_section(pdf, "Password Analysis", [
                ("Masked Password", analysis.get("password_masked", "N/A")),
                ("Length", str(analysis.get("length", 0))),
                ("Score", f"{analysis.get('score', 0)}/100"),
                ("Strength", analysis.get("strength_label", "N/A")),
                ("Entropy", f"{analysis.get('entropy_bits', 0):.2f} bits"),
                ("Crack Time", analysis.get("crack_time", "N/A")),
                ("Character Set Size", str(analysis.get("charset_size", 0))),
            ])

        breach = data.get("breach_count")
        if breach is not None:
            self._pdf_section(pdf, "Breach Check", [
                ("Breach Count", str(breach)),
                ("Risk Level", data.get("risk_level", "N/A")),
            ])

        findings = analysis.get("pattern_findings", [])
        if findings:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(220, 50, 50)
            pdf.cell(0, 8, "Security Findings:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            for f in findings:
                pdf.multi_cell(0, 6, f"  - {f}")
            pdf.ln(3)

        suggestions = analysis.get("suggestions", [])
        if suggestions:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 150, 80)
            pdf.cell(0, 8, "Recommendations:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            for s in suggestions:
                pdf.multi_cell(0, 6, f"  - {s}")
            pdf.ln(3)

        explanation = data.get("explanation")
        if explanation:
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 100, 200)
            pdf.cell(0, 8, "AI Explanation:", ln=True)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 60)
            # Remove markdown formatting for PDF
            clean = explanation.replace("**", "").replace("*", "")
            pdf.multi_cell(0, 6, clean)

        # Footer
        pdf.set_y(-25)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 10, "Generated by Password Strength & Leak Checker AI Pro", align="C")

        return bytes(pdf.output())

    @staticmethod
    def _pdf_section(pdf, title: str, items: list[tuple[str, str]]):
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 100, 200)
        pdf.cell(0, 8, title, ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        for label, value in items:
            pdf.cell(60, 6, f"  {label}:", border=0)
            pdf.cell(0, 6, value, border=0, ln=True)
        pdf.ln(3)